GRANT CREATEDB ON SYSTEM TO '${DB2_OWNER}';
GRANT CREATEDBA ON SYSTEM TO '${DB2_OWNER}';
GRANT CREATEDBC ON SYSTEM TO '${DB2_OWNER}';
GRANT CREATESG ON SYSTEM TO '${DB2_OWNER}';
GRANT BINDADD ON SYSTEM TO '${DB2_OWNER}';
GRANT DBADM ON DATABASE CBSA TO '${DB2_OWNER}';
GRANT USE OF BUFFERPOOL BP1 TO '${DB2_OWNER}';
GRANT USE OF BUFFERPOOL BP2 TO '${DB2_OWNER}';