-- Grant execute authority on CBSA plan and table access
-- Copyright IBM Corp. 2023, 2025

SET CURRENT SQLID = '${DB2_OWNER}';

GRANT EXECUTE ON PLAN ${CBSA_PLAN} TO ${BANK_USER};

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE
    ${DB2_OWNER}.ACCOUNT TO ${BANK_USER};

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE
    ${DB2_OWNER}.PROCTRAN TO ${BANK_USER};

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE
    ${DB2_OWNER}.CONTROL TO ${BANK_USER};