-- Bind DB2 packages for CBSA application
-- Copyright IBM Corp. 2023, 2025

DSN SYSTEM(${DB2_SYSTEM})

BIND PACKAGE(${CBSA_PACKAGE}) OWNER(${DB2_OWNER}) -
QUALIFIER(${DB2_OWNER}) -
MEMBER(CREACC) -
ACTION(REPLACE)

BIND PACKAGE(${CBSA_PACKAGE}) OWNER(${DB2_OWNER}) -
QUALIFIER(${DB2_OWNER}) -
MEMBER(CRECUST) -
ACTION(REPLACE)

BIND PACKAGE(${CBSA_PACKAGE}) OWNER(${DB2_OWNER}) -
QUALIFIER(${DB2_OWNER}) -
MEMBER(DBCRFUN) -
ACTION(REPLACE)

BIND PACKAGE(${CBSA_PACKAGE}) OWNER(${DB2_OWNER}) -
QUALIFIER(${DB2_OWNER}) -
MEMBER(DELACC) -
ACTION(REPLACE)

BIND PACKAGE(${CBSA_PACKAGE}) OWNER(${DB2_OWNER}) -
QUALIFIER(${DB2_OWNER}) -
MEMBER(DELCUS) -
ACTION(REPLACE)

BIND PACKAGE(${CBSA_PACKAGE}) OWNER(${DB2_OWNER}) -
QUALIFIER(${DB2_OWNER}) -
MEMBER(INQACC) -
ACTION(REPLACE)

BIND PACKAGE(${CBSA_PACKAGE}) OWNER(${DB2_OWNER}) -
QUALIFIER(${DB2_OWNER}) -
MEMBER(INQACCCU) -
ACTION(REPLACE)

BIND PACKAGE(${CBSA_PACKAGE}) OWNER(${DB2_OWNER}) -
QUALIFIER(${DB2_OWNER}) -
MEMBER(BANKDATA) -
ACTION(REPLACE)

BIND PACKAGE(${CBSA_PACKAGE}) OWNER(${DB2_OWNER}) -
QUALIFIER(${DB2_OWNER}) -
MEMBER(UPDACC) -
ACTION(REPLACE)

BIND PACKAGE(${CBSA_PACKAGE}) OWNER(${DB2_OWNER}) -
QUALIFIER(${DB2_OWNER}) -
MEMBER(XFRFUN) -
ACTION(REPLACE)

BIND PLAN(${CBSA_PLAN}) -
OWNER(${DB2_OWNER}) -
ISOLATION(UR) -
PKLIST( -
NULLID.*,${CBSA_PACKAGE}..* )

END