SET CURRENT SQLID = '${DB2_OWNER}';

DROP INDEX ${DB2_OWNER}.CONTINDX;
DROP TABLE CONTROL;
DROP TABLESPACE CONTROL;
DROP STOGROUP ${CBSA_CONTROL_STOGROUP};

DROP TABLE PROCTRAN;
DROP TABLESPACE PROCTRAN;
DROP STOGROUP ${CBSA_PROCTRAN_STOGROUP};

DROP INDEX ${DB2_OWNER}.ACCTCUST;
DROP INDEX ${DB2_OWNER}.ACCTINDX;
DROP TABLE ${DB2_OWNER}.ACCOUNT;
DROP TABLESPACE ACCOUNT;
DROP STOGROUP ${CBSA_ACCOUNT_STOGROUP};

DROP DATABASE ${CBSA_DB};
